services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    # volumes:
    #   - ./src:/app
    # restart: unless-stopped

  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - API_URL=http://backend:8000  # Optional, for Streamlit if needed
  #   volumes:
  #     - ./src:/app
  #   depends_on:
  #     - backend
  #   restart: unless-stopped